@startuml
title Блок-схема: добавление дохода/расхода

start

repeat
  :Ввод суммы;
  if (Сумма введена верно?) then (нет)
    :Вывести ошибку;
  endif
repeat while (Сумма введена верно?) is (нет)

repeat
  :Ввод категории;
  if (Категория выбрана?) then (нет)
    :Вывести ошибку;
  endif
repeat while (Категория выбрана?) is (нет)

:Сохранить в базе данных;

stop

@enduml
